[tools]
terraform = "1.13.3"
trivy = "0.66.0"
tflint = "0.59.1"
terraform-docs = "0.20.0"
python = "3.13.7"
pipx = "latest"
"pipx:pre-commit" = "latest"

[tasks]
precommit = "pre-commit run --all-files"
